### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by ppamorim** [iammert/ProgressLayout#2]
Would me amazing to implement a CI to validate the code, what do you think about?

**Comment by iammert** [comment]
Thanks for advice @ppamorim . I didn't experience about continuous integration before.But I will try to implement it as soon as possible and ping you back when it s done.

**Comment by muratcanbur** [comment]
soon I will come up with a cool documentation about CI and Android ;)

**Comment by iammert** [comment]
@muratcanbur looking forward.. :)
